name: docker

on:
  workflow_call:
    inputs:
      upload_to_artifact:
        type: boolean
        default: false
        required: false
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nano-interactive/cassandra-php-driver
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Run CMake Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_CXX_FLAGS="-fPIC" \
            -DCMAKE_C_FLAGS="-fPIC" \
            -DCMAKE_BUILD_TYPE=RELEASE \
            -DCASS_USE_STATIC_LIBS=ON \
            -DCASS_BUILD_STATIC=ON \
            -DCASS_BUILD_SHARED=ON \
            -DCASS_USE_TIMERFD=ON \
            -DLIBUV_LIBRARY=. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLINK_STATICALLY=ON ..
          ninja
          ninja install
      - uses: actions/upload-artifact@v2
        if: ${{ inputs.upload_to_artifact }}
        with:
          name: cassandra.so
          path: build/lib/cassandra.so
